### ISSUE TITLE
Cookbook does not work on ubuntu systems

### ISSUE THREAD

**Issue by ajsharp** [jtimberman/mosh-cookbook#13]
I believe this is because the metadata file depends on yum. I get a "package not found "yum" when I run it.

**Comment by jtimberman** [comment]
That only tells Chef that the yum cookbook is required. Chef doesn't support per-platform dependencies, so we have to eat all of them, otherwise we could have broken systems.

I recently added test kitchen support, and it tests on ubuntu (14.04) and centos (6.5). Everything seems to be working fine on Ubuntu, so I'll close this.
